### ISSUE TITLE
Revize modulu

### ISSUE THREAD

**Issue by ChroustJan** [mlab-modules/RFIQINT02#4]
@kaklik bude se na modulu něco upravovat?

**Comment by ChroustJan** [comment]
Bude napájeno z BATPOWER04C

**Comment by kaklik** [comment]
> Bude napájeno z BATPOWER04C

To nejde, ten ruší. Teď je tam použit ten třívýstupový měnič pro Kováře, který nevim kde má modul. Ještě je možnost na těch 3.3 asi použít nějaký lineární stabilizátor, ale zas to zvedne celkový odběr zařízení.

**Comment by ChroustJan** [comment]
@kaklik tím pádem máme problém a není vyřešené kompletně blokové schéma bleskodetektoru.

**Comment by ChroustJan** [comment]
Modul je to tento: [BATPOWER05A](https://github.com/MLAB-project/Modules/tree/master/power_supply/BATPOWER05A)

**Comment by kaklik** [comment]
> Modul je to tento: [BATPOWER05A](https://github.com/MLAB-project/Modules/tree/master/power_supply/BATPOWER05A)

A existuje od tohoto modulu nějaká alternativa, která je nyní v produkci?  Pokud žádný takový alternativní měnič nyní není, tak zřejmě nezbývá nic jiného, než použít 3.3V z lineárního stabilizátoru na některém z ostatních modulů.
