### ISSUE TITLE
Přeslech mezi kanály

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/RFIQINT02#5]
Připojení analogových signálů SATA kabely se stíněním zapojeným do GND společně s napájením zřejmě způsobuje přeslechy mezi jednotlivými kanály. 

![image](https://user-images.githubusercontent.com/1194177/157337629-a7701869-acd8-4545-a4dd-7e66a8ee3222.png)

Je tak potřeba zvýšit efektivitu stínění a zrušit možnost vzniku smyčkových proudů. Toho lze dosáhnout přidáním RC členu 
![image](https://user-images.githubusercontent.com/1194177/157337894-3a7335fa-39a9-43a6-bb00-f7bbfc1bbe29.png)

zapojeného ke stínění konektorů J4, J1 a J3. Stejný RC člen je již použit pro stínění anténních svodů z QFHMIX. Tato úprava by měla zajistit, že zem bude k modulu přivedena pouze přes napájení a základní desku.

**Comment by ChroustJan** [comment]
Přidán RC člen.
